require([
	"pure/config",
	"collection/Array",
	"collection/ArraySet",
	"collection/EntitySet",
	"data/EntityManager",
	"data/Entity",
	"data/Model",
	"data/Property",
	"data/Association",
	"data/Observable",
	"data/StoreAdapter",
	"util/defaults",
	"util/type",
	"util/dtype",
	"util/inject",
	"util/log"
]);
